### ISSUE TITLE
node-oracle v2 support

### ISSUE THREAD

**Issue by sibelius** [CollinEstes/docker-node-oracle#17]
node-oracle change recently: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#changes-in-node-oracledb-version-20

**Comment by AlexMesser** [comment]
have the same problem.

**Comment by jpollard-cs** [comment]
+1

for now I think you can just do the following in your Dockerfile:

```
RUN mkdir -p ~/lib
RUN mv /opt/oracle/instaclient ~/lib
```

I will verify if this works as expected. Stay tuned.

**Comment by jpollard-cs** [comment]
actually assuming you are using linux all you need to do is add this to your Dockerfile:

```
ENV LD_LIBRARY_PATH /opt/oracle/instantclient
```

**Comment by CollinEstes** [comment]
if anyone wants to pr this... feel free.  I don't have the time at the moment to dig into this.

**Comment by jpollard-cs** [comment]
@CollinEstes easy enough: https://github.com/CollinEstes/docker-node-oracle/pull/21

**Comment by jpollard-cs** [comment]
actually I don't know why I thought it was not set, but this is already set so this should be compatible with node-oracledb v2 - no PR needed (and it looks like this may also be covered for node 6 and 4)

it may, however, be worth removing the old stuff in the latest version (8) for v1 compatibility because it appears node-oracledb v1 is not compatible with node 8

**Comment by jpollard-cs** [comment]
@sibelius @AlexMesser can you provide the error message you are seeing?

**Comment by cemremengu** [comment]
No problems here using `oracledb: ^2.1.2`
